#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Apartmender Supabase setup"

stage "Protect the local credential file"
say "Every hosted value stays in an ignored local file. Nothing is sent to GitHub."
if ! git check-ignore -q "$ENV_FILE"; then
  warn "$ENV_FILE is not ignored by Git. Stop and fix .gitignore before continuing."
  exit 1
fi
step "Confirm Node.js 20+ and a Docker-compatible runtime are installed."
if ! command -v node >/dev/null 2>&1; then
  warn "Node.js is missing. Install Node.js 20 or newer, then run this wizard again."
  exit 1
fi
NODE_MAJOR=$(node -p "Number(process.versions.node.split('.')[0])")
if (( NODE_MAJOR < 20 )); then
  warn "Node.js 20 or newer is required; this machine reports $(node --version)."
  exit 1
fi
if ! command -v docker >/dev/null 2>&1; then
  open_url "https://supabase.com/docs/guides/local-development/cli/getting-started"
  warn "A Docker-compatible runtime is missing. Install and start one, then run this wizard again."
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  warn "Docker is installed but its runtime is not responding. Start it, then run this wizard again."
  exit 1
fi

stage "Authenticate the Supabase CLI"
say "Supabase stores this login in native credential storage, not in the repository."
step "Complete the browser login opened by the CLI."
npx supabase login

stage "Create the hosted Free project"
say "Create one Apartmender project without entering billing details or enabling add-ons."
open_url "https://supabase.com/dashboard/new"
step "Choose an organization on the Free plan and name the project apartmender."
step "Choose the specific region Central EU (Frankfurt), code eu-central-1."
step "Generate a strong database password in your password manager and use it for the project."
step "Wait until the project reports a healthy state, then copy its 20-character ref from the URL."
if ! confirm "Does the project show Free and Central EU (Frankfurt), with no paid add-on?"; then
  warn "Stop here. This issue does not authorize billing or a different region."
  exit 1
fi
ask SUPABASE_PROJECT_REF "Paste the project ref:"
ask_secret SUPABASE_DB_PASSWORD "Paste the database password:"
if [[ ! "$SUPABASE_PROJECT_REF" =~ ^[a-z0-9]{20}$ ]]; then
  warn "The project ref must be the 20-character identifier from the Dashboard URL."
  exit 1
fi
if [[ -z "$SUPABASE_DB_PASSWORD" ]]; then
  warn "The database password cannot be empty."
  exit 1
fi
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
write_env SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"

stage "Capture the API boundary"
say "The publishable key is browser-safe. The secret key remains Operator-only."
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF/settings/api-keys"
step "In Settings → API Keys, copy the Project URL and Publishable key."
step "Create one Secret key named operator if none exists, then copy it once."
ask SUPABASE_URL "Paste the Project URL:"
ask SUPABASE_PUBLISHABLE_KEY "Paste the Publishable key:"
ask_secret SUPABASE_SECRET_KEY "Paste the Operator Secret key:"
if [[ "$SUPABASE_URL" != "https://$SUPABASE_PROJECT_REF.supabase.co" ]]; then
  warn "The Project URL does not match the project ref."
  exit 1
fi
if [[ "$SUPABASE_PUBLISHABLE_KEY" != sb_publishable_* ]]; then
  warn "Expected a modern publishable key beginning with sb_publishable_."
  exit 1
fi
if [[ "$SUPABASE_SECRET_KEY" != sb_secret_* ]]; then
  warn "Expected a modern secret key beginning with sb_secret_."
  exit 1
fi
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_PUBLISHABLE_KEY "$SUPABASE_PUBLISHABLE_KEY"
write_env SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY"
note "No value was written to a GitHub secret or repository variable."

stage "Lock the hosted Auth boundary"
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF/auth/url-configuration"
step "Set Site URL to https://thdecn.github.io/apartmender/."
step "Add exact redirects http://localhost:4173/ and http://127.0.0.1:4173/."
pause "Save URL Configuration, then press Enter."
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF/auth/providers"
step "Under User Signups, turn off Allow new users to sign up."
step "Confirm anonymous sign-ins are off. Do not configure custom SMTP."
if ! confirm "Are public signup and anonymous sign-in both disabled?"; then
  warn "Hosted Auth is not yet invite-only. Correct it before continuing."
  exit 1
fi

stage "Link and verify the hosted project"
say "Linking writes only ignored Supabase CLI state. The database password is not committed."
SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" npx supabase link --project-ref "$SUPABASE_PROJECT_REF"
npx supabase projects list
if ! confirm "Does the linked project list show eu-central-1 and an active healthy state?"; then
  warn "The hosted project does not match the recorded region and health boundary."
  exit 1
fi

stage "Exercise the reproducible local workflow"
say "This downloads the local images on first use, rebuilds the database, and runs pgTAP."
npm run supabase:start
npm run supabase:reset
npm run supabase:test
npm run supabase:stop
note "Free projects may pause. Before real onboarding, schedule off-site logical exports and rehearse restore."

finish
